name: Deploy static content to Pages

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build-thesis:
    runs-on: ubuntu-latest
    container: texlive/texlive:latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Thesis
        run: |
          cd thesis
          pdflatex main.tex
          bibtex main
          pdflatex main.tex
          pdflatex main.tex
          mkdir -p ../dist
          cp main.pdf ../dist/thesis.pdf

      - name: Upload thesis artifact
        uses: actions/upload-artifact@v4
        with:
          name: thesis-pdf
          path: './dist'

  build:
    runs-on: ubuntu-latest
    needs: build-thesis
    steps:
    - uses: actions/checkout@v4
    
    - name: Download thesis PDF
      uses: actions/download-artifact@v4
      with:
        name: thesis-pdf
        path: dist

    - uses: wranders/markdown-to-pages-action@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        files: |-
          README.md
          docs/README.md
          docs/notes/notes.md
          docs/thesis/thesis.md
          docs/pid/pid.md
          docs/plan/plan.md
          docs/reading-list/reading-list.md

    - uses: actions/upload-pages-artifact@v3
      with:
        path: dist

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
    - uses: actions/deploy-pages@v4
      id: deployment


